[colors.bright]
black = "#000000"
blue = "#61afef"
cyan = "#56b6c2"
green = "#89b064"
magenta = "#c678dd"
red = "#e06c75"
white = "#c8ccd4"
yellow = "#d1b071"

[colors.normal]
black = "#1e222a"
blue = "#305CDE"
cyan = "#0D98BA"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d1b071"

[colors.primary]
background = "#1e222a"
foreground = "#abb2bf"
